# テスト(rspec)、コードルール(rubocop, eslint, prettier)のチェックを行う
name: Continuous Integration

# 当 workflow の実行タイミング
# ブランチへの push 時
on:
  push:

# 当 workflow が行う処理
jobs:
  # 処理① rspec がオールグリーンであることをチェック
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails
    services:
      db:
        image: postgres:11.6-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: Wait for PostgreSQL to become available
          run: sleep 10
      - name: Database create and migrate
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
        env:
          PG_HOST: postgres
          RAILS_ENV: test
      - name: Run rspec
        run: bundle exec rspec

  # 処理② rubocop のルール違反がないことをチェック
  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rails
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run rubocop
        run: bundle exec rubocop

  # 処理③ eslint(& prettier) のルール違反がないことをチェック
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run lint
        run: npm run lint